name: Release

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install jupyterlab==2.2.0
          yarn
      - name: Publish
        if: ${{ steps.tagExistsAndVersion.outputs.npmTagExists == 'false'}}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.LIFEOMIC_NPM_TOKEN}}
      - name: Create Release
        if: ${{ steps.tagExistsAndVersion.outputs.npmTagExists == 'false'}}
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tagExistsAndVersion.outputs.packageVersion }}
          release_name: v${{ steps.tagExistsAndVersion.outputs.packageVersion }}
          draft: false
          prerelease: false